//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeptApp
{
    public class department
    {
        public int Deptno { get; set; }
        public string Deptname { get; set; }
        public string DeptLoc { get; set; }
    }
}